package com.jsu.js.pojo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passWord
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.marriage
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.contacts
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.carrer
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String carrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.houseRegister
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String houseRegister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hobby
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remark
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthDay
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    private Date birthDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passWord
     *
     * @return the value of user.passWord
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passWord
     *
     * @param passWord the value for user.passWord
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.marriage
     *
     * @return the value of user.marriage
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.marriage
     *
     * @param marriage the value for user.marriage
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.contacts
     *
     * @return the value of user.contacts
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.contacts
     *
     * @param contacts the value for user.contacts
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.carrer
     *
     * @return the value of user.carrer
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getCarrer() {
        return carrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.carrer
     *
     * @param carrer the value for user.carrer
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setCarrer(String carrer) {
        this.carrer = carrer == null ? null : carrer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.houseRegister
     *
     * @return the value of user.houseRegister
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getHouseRegister() {
        return houseRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.houseRegister
     *
     * @param houseRegister the value for user.houseRegister
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setHouseRegister(String houseRegister) {
        this.houseRegister = houseRegister == null ? null : houseRegister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hobby
     *
     * @return the value of user.hobby
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hobby
     *
     * @param hobby the value for user.hobby
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remark
     *
     * @return the value of user.remark
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remark
     *
     * @param remark the value for user.remark
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthDay
     *
     * @return the value of user.birthDay
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthDay
     *
     * @param birthDay the value for user.birthDay
     *
     * @mbg.generated Thu Apr 23 11:07:06 CST 2020
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }
}